### ISSUE TITLE
Please make this repo private

### ISSUE THREAD

**Issue by bathal1** [Battleman/VisComp#1]
Dear Olivier,
I am a teaching assistant at EPFL, in charge of teaching the numerical methods course.
This repository contains solutions to assignements of a course that is still being taught at EPFL. In an effort to reduce temptations to cheat for current students, we kindly ask you to make it private.

Best,
Baptiste

**Comment by Battleman** [comment]
Dear Baptiste.
Thank you for bringing it to my attention. Unfortunately I don't think I will close this repository. I believe in sharing my work with others, in an teaching effort. 
But I must say I am surprised this material is still used a second year, even less 3 more years. With students re-taking the course, getting it through students who previously took it, or through one of the thousand drive/dropbox lying around, probably not many students don't have their hands on some sort of solution! 

Best
Olivier
